Startup guide for BeagleBoard X15
=================================
:author: Gennaro Tortone (gennaro.tortone@na.infn.it)
:revision: 1.1 - November 2017 - INFN Napoli
:toc:
:toc-placement: preamble
:toclevels: 1

// Need some preamble to get TOC:
{empty}

== Introduction

- evaluation board

	TMDXEVM5728

- EVM user guide

	http://processors.wiki.ti.com/index.php/AM572x_General_Purpose_EVM_HW_User_Guide

- Linux SDK

	http://software-dl.ti.com/processor-sdk-linux/esd/AM57X/latest/index_FDS.html

- Debian for BeagleBoard X15

	https://eewiki.net/display/linuxonarm/BeagleBoard-X15

== Debian rootfs build with image-builder

- working directory

	/home/tortone/devel/Belle2/BB-X15/image-builder

- download image-builder

  git clone https://github.com/gtortone/image-builder.git

- comment following line in +configs/rcn-ee_console_debian_jessie_armhf.conf+

  rfs_opt_scripts="https://github.com/RobertCNelson/boot-scripts"

- start rootfs build

	./RootStock-NG.sh -c rcn-ee_console_debian_jessie_armhf

- the rootfs will be deployed in

  deploy/debian-8.5-console-armhf-YYYY-MM-DD

- to create a +.img+ rootfs file

  cd deploy/debian-8.5-console-armhf-YYYY-MM-DD
  sudo ./setup_sdcard.sh --img-2gb bb-x15.img --dtb am57xx-beagle-x15

- to write rootfs on uSD

  sudo ./setup_sdcard.sh --mmc /dev/sdX --dtb am57xx-beagle-x15

- add +--bbb-flasher+ option to add automatic execution of flasher at boot (useful for uSD => eMMC copy)


[TIP]
====
- kernels provided by rootfs Debian 8.5 (date 9-9-2016)

 linux-image-4.4.20-ti-r43
 linux-image-4.8.0-rc5-armv7-x1

- U-Boot fetched by image-builder (date 9-9-2016)

 https://rcn-ee.com/repos/bootloader/am57xx_evm_ti/MLO-am57xx_evm_ti-v2016.05-r9
 https://rcn-ee.com/repos/bootloader/am57xx_evm_ti/u-boot-am57xx_evm_ti-v2016.05-r9.img
====

== Debian rootfs build starting from minimal rootfs

- working directory

	/home/tortone/devel/Belle2/BB-X15/rootfs

- download minimal Debian rootfs

  wget -c  https://rcn-ee.com/rootfs/eewiki/minfs/debian-8.5-minimal-armhf-2016-08-16.tar.xz
  tar xf debian-8.5-minimal-armhf-2016-08-16.tar.xz

This Debian rootfs needs:

- a Linux bootloader
* <<howto-uboot>>
- a Linux kernel
* <<howto-kernel>>
- an installation media for deployment
* <<howto-usd>>
* <<howto-emmc>>
* <<howto-nfs>>

== Debian rootfs build with debootstrap

- working directory

	/home/tortone/devel/Belle2/BB-X15/debootstrap

- required packages on build host

	binfmt-support
	qemu-user-static
	debootstrap

- start debootstrap for Linux Debian Jessie armhf

	debootstrap --foreign --arch=armhf jessie rootfs-debian8
	cp /usr/bin/qemu-arm-static rootfs-debian8/usr/bin/
	chroot rootfs-debian8 /debootstrap/debootstrap --second-stage

- chroot

	chroot rootfs-debian8

- add these repositories to +/etc/apt/sources.list+

  deb http://httpredir.debian.org/debian/ jessie-updates main contrib non-free
  deb http://security.debian.org/ jessie/updates main contrib non-free
  deb [arch=armhf] http://repos.rcn-ee.com/debian/ jessie main

- update repositories

  apt-get update

- packages to install

  rcn-ee-archive-keyring
  initramfs-tools
  locales
  git
  rsync
  openssh-server
  python

- reconfigure +locales+ with +en_US.UTF-8+

  dpkg-reconfigure locales

- clone repository https://github.com/RobertCNelson/boot-scripts

  git clone https://github.com/RobertCNelson/boot-scripts /opt/scripts

- install a kernel package from official repository, from local .deb files
  or copy your own kernel (=> <<howto-copy-kernel>>)

  apt-get install linux-image-4.4.20-ti-r43

- set a root password

  passwd

- set +/etc/fstab+

  echo "/dev/mmcblk1p1  /  auto  errors=remount-ro  0  1" >> /etc/fstab

- exit from chroot

- copy U-Boot from local build or fetch it from https://rcn-ee.com/repos/bootloader/am57xx_evm_ti

  cp u-boot/u-boot-spl.bin debootstrap/rootfs-debian8/boot
  cp u-boot/u-boot.img debootstrap/rootfs-debian8/boot

This Debian rootfs needs:

- an installation media for deployment
* <<howto-usd>>
* <<howto-emmc>>
* <<howto-nfs>>

== Post installation tasks

- set a root password

  passwd

- set +/etc/ssh/sshd_config+ for root authentication and no DNS use

  PermitRootLogin yes
  UseDNS no

- configure eth0 and eth1 network interfaces in +/etc/network/interfaces+

  auto lo
  iface lo inet loopback
  auto eth0
  iface eth0 inet dhcp
  auto eth1
  iface eth1 inet dhcp

- set hostname (e.g. x15) in +/etc/hostname+

= Appendix

[[howto-linaro]]
== LINARO compiler installation and configuration

- working directory

  /home/tortone/devel/Belle2/BB-X15/gcc

- download and untar

  wget -c https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/arm-linux-gnueabihf/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf.tar.xz

- set CC environment variable

  export CC=/home/tortone/devel/Belle2/BB-X15/gcc/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-

[[howto-uboot]]
== How to build U-Boot for BeagleBoard X15

- working directory

	/home/tortone/devel/Belle2/BB-X15/u-boot

- download

  git clone https://github.com/u-boot/u-boot

TIP: U-Boot release used: v2016.05

- checkout

  cd u-boot
  git checkout v2016.05 -b tmp

- patches

	git pull --no-edit git://git.ti.com/ti-u-boot/ti-u-boot.git ti-u-boot-2016.05
	wget -c https://rcn-ee.com/repos/git/u-boot-patches/ti-2016.05/0001-beagle_x15-uEnv.txt-bootz-n-fixes.patch
	patch -p1 < 0001-beagle_x15-uEnv.txt-bootz-n-fixes.patch

- build

	export CC=/home/tortone/devel/Belle2/BB-X15/gcc/gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
	make ARCH=arm CROSS_COMPILE=${CC} distclean
	make ARCH=arm CROSS_COMPILE=${CC} am57xx_evm_config
	make ARCH=arm CROSS_COMPILE=${CC}

- to enable ethernet and UART (YModem) support add these define to

	include/configs/am57xx_evm.h

  #define CONFIG_SPL_ETH_SUPPORT		!!! to check !!!
  #define CONFIG_SPL_NET_SUPPORT		!!! to check !!!
  #define CONFIG_SPL_YMODEM_SUPPORT

[NOTE]
====
- to send U-Boot bootloader through UART use utilities available on this repository

	https://github.com/nmenon/omap-u-boot-utils

- for spl/u-boot-spl.bin (MLO) use this command

	pserial -p /dev/ttyUSB0 -f spl/u-boot-spl.bin

- for u-boot.img (bootloader) use this command

	sb u-boot.img < /dev/ttyUSB0 > /dev/ttyUSB0
====

- it is possible to download pre-built binary (MLO, u-boot) from

  https://rcn-ee.com/repos/bootloader/am57xx_evm_ti

[[howto-kernel]]
== How to build Linux Kernel for BeagleBoard X15

=== TI release

- working directory

	/home/tortone/devel/Belle2/BB-X15/ti-linux-kernel-dev

- download

 git clone https://github.com/RobertCNelson/ti-linux-kernel-dev.git
 cd ti-linux-kernel-dev
 git checkout 4.4.x -b tmp

TIP: TI kernel release used: 4.4.20-ti-r43

=== Mainline release

- working directory

	/home/tortone/devel/Belle2/BB-X15/linux-dev

- download

 git clone https://github.com/RobertCNelson/linux-dev.git
 cd linux-dev

TIP: kernel release used: 4.14.0-rc8


=== Build scripts

first build:

	./build_kernel.sh

next builds:

	./tools/rebuild.sh

to make Debian packages:

	./tools/rebuild_deb.sh

[[howto-copy-kernel]]
== How to copy Linux Kernel to rootfs

- move to Linux Kernel build directory

- identify release from +kernel_version+ file

  export kernel_version=4.4.8-ti-r23

- set rootfs working directory

  export rootfs_dir=/media/rootfs

- set release in U-Boot setup file

  sudo sh -c "echo uname_r=${kernel_version} >> ${rootfs_dir}/boot/uEnv.txt"

- copy kernel image

  sudo cp -v deploy/${kernel_version}.zImage ${rootfs_dir}/boot/vmlinuz-${kernel_version}

- copy device tree files

  sudo mkdir -p ${rootfs_dir}/boot/dtbs/${kernel_version}
  sudo tar xfv deploy/${kernel_version}-dtbs.tar.gz -C ${rootfs_dir}/boot/dtbs/${kernel_version}

- copy kernel modules

  sudo tar xfv deploy/${kernel_version}-modules.tar.gz -C ${rootfs_dir}

- setup /etc/fstab

  sudo sh -c "echo '/dev/mmcblk1p1  /  auto  errors=remount-ro  0  1' >> ${rootfs_dir}/etc/fstab"

- setup network interfaces in +/etc/network/interfaces+

  auto lo
  iface lo inet loopback

  auto eth0
  iface eth0 inet dhcp

  auto eth1
  iface eth1 inet dhcp

- commit changes to filesystem

  sync

[[howto-usd]]
== How to deploy rootfs on uSD

=== uSD initialization

- identify Linux device mapped to uSD with +dmesg+ command

  export DISK=/dev/sdX

- erase uSD

  sudo dd if=/dev/zero of=${DISK} bs=1M count=10

- raw write of U-Boot

  sudo dd if=./u-boot/MLO of=${DISK} count=1 seek=1 bs=128k
  sudo dd if=./u-boot/u-boot.img of=${DISK} count=2 seek=1 bs=384k

- create rootfs partition

  sudo sfdisk --unit M ${DISK} << __EOF__
  1,,L,*
  __EOF__

- format rootfs partition

	sudo mkfs.ext4 -L rootfs ${DISK}1

- create local mountpoint

  sudo mkdir -p /media/rootfs

- mount rootfs

	sudo mount ${DISK}1 /media/rootfs

- follow the <<howto-copy-kernel>>

=== rootfs copy

- copy rootfs to uSD

  rsync -va {rootfs_dir} /media/rootfs

- insert uSD and boot X15

[[howto-nfs]]
== How to deploy rootfs on NFS / TFTP

- copy rootfs to NFS directory

  rsync -va ${rootfs_dir} /srv/nfs/x15-rootfs

- copy kernel and device tree to TFTP directory

  cp ${rootfs_dir}/boot/vmlinuz-4.4.20-ti-r43 /srv/tftp/x15-vmlinuz
  cp ${rootfs_dir}/boot/dtbs/4.4.20-ti-r43/am57xx-beagle-x15-revb1.dtb /srv/tftp

- setup DHCP with +/etc/dhcp/dhcpd.conf+

  host x15 {
       hardware ethernet a0:f6:fd:a6:7f:06;
       fixed-address 10.1.1.31;
       option root-path "/srv/nfs/x15-rootfs";
       filename "x15-vmlinuz";
  }

- boot X15 and stop U-Boot execution

- from U-Boot command line

  run findfdt
  run netboot

[[howto-emmc]]
== How to deploy rootfs on eMMC

- boot BeagleBoard X15 by uSD or NFS and launch the script

  /opt/scripts/tools/eMMC/init-eMMC-flasher-v3-x15_b1.sh

- if flasher script it is not available get it from Git repository

  https://github.com/RobertCNelson/boot-scripts
